# Generated by Django 2.2.1 on 2019-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0001_createsuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_openid', models.CharField(max_length=64)),
                ('work_tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.CharField(default='{}', max_length=10000)),
                ('max_votes', models.IntegerField(default=1)),
            ],
        ),
    ]
